name: Vagrant Box Builder

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted # as 13 is the latest intel arch

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Download and extract ubuntu server cloudimage
        run: |
          ls -al
          curl -LO https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.ova
          tar --extract -f noble-server-cloudimg-amd64.ova ubuntu-noble-24.04-cloudimg.ovf
          tar --delete -f noble-server-cloudimg-amd64.ova ubuntu-noble-24.04-cloudimg.ovf
          mv ubuntu-noble-24.04-cloudimg.ovf box.ovf
          tar --append -f noble-server-cloudimg-amd64.ova box.ovf
          rm box.ovf

      - name: Add the box to vagrant
        run: |
          vagrant box add --name noble64 ./noble-server-cloudimg-amd64.ova
          vagrant box list
          vagrant plugin install vagrant-vbguest

      - name: Startup the instance
        run: |
          vagrant up

      - name: Remove noble64 box
        run: |
          vagrant box remove noble64

      # Run Bartender
      #- name: Run a multi-line script
      #  run: |
      #    git clone https://github.com/ubuntu-bartenders/ubuntu-old-fashioned.git
      #    cd ubuntu-old-fashioned/scripts/ubuntu-bartender/
      #    sudo ./ubuntu-bartender --livecd-rootfs-branch ubuntu/noble --build-provider multipass -- --series noble --image-target vagrant --project ubuntu-cpc
