name: Vagrant Box Builder

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-13 # as 13 is the latest intel arch

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Upgrade Homebrew
        run: brew update && brew upgrade

      - name: Install Virtualbox and vagrant
        run: |
          brew install --cask virtualbox
          brew install --cask vagrant
          VBoxManage --version
          vagrant --version

      - name: Download and extract ubuntu server cloudimage
        run: |
          curl -LO https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.ova


      # Run Bartender
      #- name: Run a multi-line script
      #  run: |
      #    git clone https://github.com/ubuntu-bartenders/ubuntu-old-fashioned.git
      #    cd ubuntu-old-fashioned/scripts/ubuntu-bartender/
      #    sudo ./ubuntu-bartender --livecd-rootfs-branch ubuntu/noble --build-provider multipass -- --series noble --image-target vagrant --project ubuntu-cpc
