name: Vagrant Box Builder

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y petname git

      - name: Install dependencies
        run: sudo snap install multipass

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: git clone https://github.com/ubuntu-bartenders/ubuntu-old-fashioned.git

      # Run Bartender
      - name: Run a multi-line script
        run: |
          cd ubuntu-old-fashioned/scripts/ubuntu-bartender/
          ./ubuntu-bartender \
          --livecd-rootfs-branch ubuntu/jammy \
          --build-provider multipass \
          -- \
          --series jammy \
          --image-target vagrant \
          --project ubuntu-cpc
